#!/usr/bin/env python3
"""Write the factor dictionary tables from factors-daybar's library documents.

factors-daybar keeps one folder per library (``libraries/<owner>/<library>/README.md``); between the
``factors:begin`` / ``factors:end`` markers each README carries a table generated from the factor
registry: factor, group, formula, meaning, lookback, storage. This script turns those tables into
reStructuredText list-tables under ``docs/_shared/tables/factors/`` that both documentation trees
include, so the dictionary is never edited by hand and never drifts from the registry.

Usage (from the repository root)::

    git clone https://github.com/StateOfTheArt-quant/factors-daybar /tmp/factors-daybar
    python docs/_shared/generate_factor_dictionary.py /tmp/factors-daybar/libraries
    python docs/_shared/generate_factor_dictionary.py /tmp/factors-daybar/libraries --check   # stale -> exit 1
"""
from __future__ import annotations

import argparse
import pathlib
import re
import sys

REPO = pathlib.Path(__file__).resolve().parents[2]
OUT = REPO / "docs" / "_shared" / "tables" / "factors"

# The definition libraries. system/alpha158 refers to system/qlib in Qlib order: same factors, no table.
LIBRARIES = ["system/qlib", "system/barra-cne5", "system/barra-cne5-descriptor", "system/barra-cne6-descriptor"]
HEADERS = {
    "zh": ["因子", "分组", "公式", "含义", "lookback", "存储"],
    "en": ["Factor", "Group", "Formula", "Meaning (zh)", "Lookback", "Storage"],
}
STORAGE = {
    "zh": {"稠密": "稠密", "阶梯": "阶梯", "运行时（截面）": "截面"},
    "en": {"稠密": "dense", "阶梯": "step", "运行时（截面）": "runtime"},
}
ROW = re.compile(r"^\| `(?P<factor>[^`]+)` \| (?P<group>[^|]*) \| (?P<formula>.*) \| (?P<meaning>[^|]*) \| "
                 r"(?P<lookback>[^|]*) \| (?P<storage>[^|]*) \|$")


def rows(readme: pathlib.Path) -> list[dict]:
    text = readme.read_text(encoding="utf-8")
    begin, end = text.find("<!-- factors:begin"), text.find("<!-- factors:end")
    if begin < 0 or end < 0:
        raise SystemExit(f"{readme}: no factors:begin / factors:end markers")
    out = []
    for line in text[begin:end].splitlines():
        if line.startswith("| `"):
            m = ROW.match(line.strip())
            if not m:
                raise SystemExit(f"{readme}: cannot read the row {line!r}")
            out.append({k: v.strip() for k, v in m.groupdict().items()})
    if not out:
        raise SystemExit(f"{readme}: the factor table is empty")
    return out


def literal(code: str) -> str:
    """A Markdown code span's text as an RST inline literal."""
    code = code.strip()
    if code.startswith("`") and code.endswith("`"):
        code = code[1:-1]
    return "``" + code.replace("``", "` `") + "``" if code else ""


def prose(text: str) -> str:
    """Markdown prose as RST: code spans become literals, markup characters are escaped."""
    parts = re.split(r"(`[^`]+`)", text)
    out = []
    for part in parts:
        if part.startswith("`") and part.endswith("`") and len(part) > 1:
            out.append("\\ " + literal(part) + "\\ ")
        else:
            out.append(re.sub(r"([*|_\\])", r"\\\1", part))
    return "".join(out).strip()


def table(library: str, items: list[dict], language: str) -> str:
    lines = [f".. Generated by docs/_shared/generate_factor_dictionary.py from factors-daybar"
             f" libraries/{library}/README.md -- do not edit.", "",
             ".. list-table::", "   :header-rows: 1", "   :widths: 15 8 28 33 8 8", ""]
    lines.append("   * - " + "\n     - ".join(HEADERS[language]))
    for item in items:
        storage = STORAGE[language].get(item["storage"], item["storage"])
        cells = [literal(item["factor"]), prose(item["group"]), literal(item["formula"]),
                 prose(item["meaning"]), item["lookback"], storage]
        lines.append("   * - " + "\n     - ".join(cell or "\\-" for cell in cells))
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("libraries", type=pathlib.Path, help="factors-daybar's libraries/ directory")
    parser.add_argument("--check", action="store_true", help="exit 1 when a written table is stale")
    args = parser.parse_args()
    stale = []
    for library in LIBRARIES:
        items = rows(args.libraries / library / "README.md")
        for language in HEADERS:
            path = OUT / f"{library.split('/')[1]}.{language}.rst"
            text = table(library, items, language)
            if path.exists() and path.read_text(encoding="utf-8") == text:
                continue
            stale.append(path)
            if not args.check:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(text, encoding="utf-8")
        print(f"{library}: {len(items)} factors")
    for path in stale:
        print(("stale: " if args.check else "wrote: ") + str(path.relative_to(REPO)))
    return 1 if args.check and stale else 0


if __name__ == "__main__":
    sys.exit(main())
