[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "libfinance"
version = "0.0.3"

dependencies = ["lz4","msgpack","pandas>=1.3.4"]
description = "libfinance is a modern finance API"
readme = "README.md"